products = [
    {
        '_id':'1',
        'name' : 'Airpods Wireless Bluetooth Headphones',
        'image' : '/images/airpods3.jpg',
        'description' : 'Bluetooth technology lets you to connect with compatible devices wirelessly high quality',
        'brand' : 'Apple',
        'category' : 'Electronics',
        'price' : 89.99,
        'countInStock' : 10,
        'rating' : 4.5,
        'numReviews' : 12,
    },
    {
        '_id' : '2',
        'name' : 'Airpods Wireless Bluetooth Headphones',
        'image' : '/images/airpods3.jpg',
        'description' : 'Bluetooth technology lets you to connect with compatible devices wirelessly high quality',
        'brand' : 'Apple',
        'category' : 'Electronics',
        'price' : 89.99,
        'countInStock' : 10,
        'rating' : 4.5,
        'numReviews' : 12,
    },
    {
        '_id' : '3',
        'name' : 'Airpods Wireless Bluetooth Headphones',
        'image' : '/images/airpods3.jpg',
        'description' : 'Bluetooth technology lets you to connect with compatible devices wirelessly high quality',
        'brand' : 'Apple',
        'category' : 'Electronics',
        'price' : 89.99,
        'countInStock' : 10,
        'rating' : 4.5,
        'numReviews' : 12,
    },
    {
        '_id' : '4',
        'name' : 'Airpods Wireless Bluetooth Headphones',
        'image' : '/images/airpods3.jpg',
        'description' : 'Bluetooth technology lets you to connect with compatible devices wirelessly high quality',
        'brand' : 'Apple',
        'category' : 'Electronics',
        'price' : 89.99,
        'countInStock' : 10,
        'rating' : 4.5,
        'numReviews' : 12,
    },
    {
        '_id' : '5',
        'name' : 'Airpods Wireless Bluetooth Headphones',
        'image' : '/images/airpods3.jpg',
        'description' : 'Bluetooth technology lets you to connect with compatible devices wirelessly high quality',
        'brand' : 'Apple',
        'category' : 'Electronics',
        'price' : 89.99,
        'countInStock' : 10,
        'rating' : 4.5,
        'numReviews' : 12,
    },
]